### Request the proxy process to execute shell command.
POST http://localhost:8080/execute
Content-Type: application/x-www-form-urlencoded

cmd=echo hello

### Request a specific blockchain process to retrieve consensus status.
GET http://localhost:8080/proxy/-1/consensus

### Request a specific blockchain process to retrieve txpool status.
GET http://localhost:8080/proxy/-1/txpool

### Request a specific blockchain process to retrieve block at specified height.
GET http://localhost:8080/proxy/-1/blocks/height/10

### Request a specific blockchain process to stream the log file.
# curl http://localhost:8080/stream/-1

### Request the proxy process to one-click start a local cluster.
POST http://localhost:8080/setup/oneclick
Content-Type: application/json

{
  "nodeCount": 4,
  "stakeQuota": 9999,
  "windowSize": 4
}

### 1.1 Request the proxy process to new a local cluster factory.
POST http://localhost:8080/setup/new/factory
Content-Type: application/json

{
  "nodeCount": 4,
  "stakeQuota": 9999,
  "windowSize": 4
}

### 1.2 Request the proxy process to reset the working directory.
POST http://localhost:8080/setup/reset/workdir

### 1.3 Request the proxy process to make local point and topic addresses.
POST http://localhost:8080/setup/genesis/addrs

### 1.4 Request the proxy process to make validator keys and stake quotas.
POST http://localhost:8080/setup/genesis/random

### 1.5 Request the proxy process to write the genesis files for startup.
POST http://localhost:8080/setup/genesis/template

### 1.6 Request the proxy process to new a cluster named cluster_template.
POST http://localhost:8080/setup/new/cluster

### 1.7 Request the proxy process to build the blockchain binary file.
POST http://localhost:8080/setup/build/chain

### Request the proxy process to view the working directory of each node.
GET http://localhost:8080/workdir/0/genesis.json

### 1.8 Request the proxy process to start the cluster.
POST http://localhost:8080/setup/cluster/start

### Request the proxy process to stop the cluster.
POST http://localhost:8080/setup/cluster/stop

### Request the proxy process to check liveness of the cluster.
GET http://localhost:8080/setup/cluster/liveness

### 2.1 Request the proxy process to new a transaction client.
POST http://localhost:8080/transaction/new/client

### 2.2 Request the proxy process to upload an evm contract.
POST http://localhost:8080/transaction/upload/contract
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Storage.sol"
Content-Type: text/plain

< ../../evm/testdata/contracts/Storage.sol
--WebAppBoundary--

### Request the proxy process to upload a bincc chaincode.
POST http://localhost:8080/transaction/upload/bincc

### 2.3 Request the proxy process to deploy the uploaded contract.
POST http://localhost:8080/transaction/deploy/contract
Content-Type: application/json

{
  "class": "Storage",
  "params": [],
  "types": []
}

### 2.4 Request the proxy process to invoke the deployed contract.
POST http://localhost:8080/transaction/invoke/contract
Content-Type: application/json

{
  "method": "store",
  "params": [
    "1024"
  ],
  "types": [
    "uint256"
  ]
}

### 2.5 Request the proxy process to query the deployed contract.
POST http://localhost:8080/transaction/query/contract
Content-Type: application/json

{
  "method": "retrieve",
  "params": [],
  "types": []
}

### Request the score of setup.
GET http://localhost:8080/score/setup